
class Config {

    static applicationId = 'com.wlq.willymodule'
    static appName = 'WillyModule'

    static compileSdkVersion = 30
    static minSdkVersion = 19
    static targetSdkVersion = 30
    static versionCode = 1_000_000
    static versionName = '1.0.0'

    static gradlePluginVersion = '4.1.3'
    static kotlinVersion = '1.3.70'
    static ktxVersion = '1.2.0'
    static supportVersion = '28.1.1'

    static byteXVersion = '0.3.0'

    static modules = [
            /*Don't delete this line*/
            /*Generated by "module_config.json"*/
            plugin_api_gradle_plugin   : new ModuleConfig(isApply: true , useLocal: true , localPath: "./plugin/api-gradle-plugin"),
            plugin_bus_gradle_plugin   : new ModuleConfig(isApply: true , useLocal: true , localPath: "./plugin/bus-gradle-plugin"),
            plugin_method_trace_plugin : new ModuleConfig(isApply: true , useLocal: true , localPath: "./plugin/method-trace-plugin"),
            plugin_start_up_plugin     : new ModuleConfig(isApply: true , useLocal: true , localPath: "./plugin/start-up-plugin"),
            plugin_lib_base_transform  : new ModuleConfig(isApply: true , useLocal: true , localPath: "./plugin/lib/base-transform", remotePath: "io.github.weiliqiang:base-transform:1.0.6"),
            feature_mock               : new ModuleConfig(isApply: false, useLocal: true , localPath: "./feature/mock"),
            feature_launcher_app       : new ModuleConfig(isApply: false, useLocal: true , localPath: "./feature/launcher/app"),
            feature_launcher_export    : new ModuleConfig(isApply: true , useLocal: true , localPath: "./feature/launcher/export"),
            feature_launcher_pkg       : new ModuleConfig(isApply: true , useLocal: true , localPath: "./feature/launcher/pkg"),
            feature_feature0_app       : new ModuleConfig(isApply: false, useLocal: true , localPath: "./feature/feature0/app"),
            feature_feature0_export    : new ModuleConfig(isApply: true , useLocal: true , localPath: "./feature/feature0/export"),
            feature_feature0_pkg       : new ModuleConfig(isApply: true , useLocal: true , localPath: "./feature/feature0/pkg"),
            feature_feature1_app       : new ModuleConfig(isApply: false, useLocal: true , localPath: "./feature/feature1/app"),
            feature_feature1_export    : new ModuleConfig(isApply: true , useLocal: true , localPath: "./feature/feature1/export"),
            feature_feature1_pkg       : new ModuleConfig(isApply: true , useLocal: true , localPath: "./feature/feature1/pkg"),
            feature_feature2_app       : new ModuleConfig(isApply: true , useLocal: true , localPath: "./feature/feature2/app"),
            feature_feature2_export    : new ModuleConfig(isApply: true , useLocal: true , localPath: "./feature/feature2/export"),
            feature_feature2_pkg       : new ModuleConfig(isApply: true , useLocal: true , localPath: "./feature/feature2/pkg"),
            lib_base                   : new ModuleConfig(isApply: true , useLocal: true , localPath: "./lib/base", remotePath: "io.github.weiliqiang:lib_base:1.0.1"),
            lib_common                 : new ModuleConfig(isApply: true , useLocal: true , localPath: "./lib/common", remotePath: "io.github.weiliqiang:lib_common:1.0.1"),
            /*Don't delete this line*/
    ]

    static plugins = [
            plugin_gradle       : new PluginConfig(path: "com.android.tools.build:gradle:$gradlePluginVersion"),
            plugin_kotlin       : new PluginConfig(path: "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"),
            plugin_bytex        : new PluginConfig(path: "com.bytedance.android.byteX:base-plugin:$byteXVersion"),

            plugin_api          : new PluginConfig(isApply: true, useLocal: false, path: "io.github.weiliqiang:api-gradle-plugin:1.0.10", id: "io.github.weiliqiang.api"),
            plugin_bus          : new PluginConfig(isApply: true, useLocal: false, path: "io.github.weiliqiang:bus-gradle-plugin:1.0.2", id: "io.github.weiliqiang.bus"),
            plugin_mehtodTrace  : new PluginConfig(isApply: true, useLocal: false, path: "io.github.weiliqiang:methodTrace-plugin:1.0.3", id: "io.github.weiliqiang.methodTrace"),
            plugin_startUp      : new PluginConfig(isApply: true, useLocal: false, path: "io.github.weiliqiang:startUp-plugin:1.0.3", id: "io.github.weiliqiang.startUp")
    ]

    static libs = [
            appcompat                   : new LibConfig(path: "androidx.appcompat:appcompat:1.2.0"),
            androidx_multidex           : new LibConfig(path: "androidx.multidex:multidex:2.0.1"),
            androidx_constraint         : new LibConfig(path: "androidx.constraintlayout:constraintlayout:2.1.3"),

            kotlin                      : new LibConfig(path: "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlinVersion"),
            kotlin8                     : new LibConfig(path: "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlinVersion"),
            ktx                         : new LibConfig(path: "androidx.core:core-ktx:$ktxVersion"),
            kotlin_coroutines           : new LibConfig(path: "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.9"),
            kotlin_coroutines_Android   : new LibConfig(path: "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.9"),

            retrofit                    : new LibConfig(path: "com.squareup.retrofit2:retrofit:2.9.0"),
            okhttp                      : new LibConfig(path: "com.squareup.okhttp3:okhttp:4.9.3"),
            gson                        : new LibConfig(path: "com.google.code.gson:gson:2.9.0"),
            glide                       : new LibConfig(path: "com.github.bumptech.glide:glide:4.13.0"),
            glide_processor             : new LibConfig(path: "com.github.bumptech.glide:compiler:4.13.0"),
            utilcode                    : new LibConfig(path: "com.blankj:utilcode:1.28.0"),
            free_proguard               : new LibConfig(path: "com.blankj:free-proguard:1.0.1"),
            swipe_panel                 : new LibConfig(path: "com.blankj:swipe-panel:1.1"),
            commons_io                  : new LibConfig(path: "commons-io:commons-io:2.6"),

            leakcanary_android          : new LibConfig(path: "com.squareup.leakcanary:leakcanary-android:2.1"),

            bytex_common                : new LibConfig(path: "com.bytedance.android.byteX:common:$byteXVersion"),
            bytex_processor             : new LibConfig(path: "com.bytedance.android.byteX:PluginConfigProcessor:$byteXVersion")
    ]
}