class Config {

    static applicationId = 'com.wlq.willymodule'
    static appName = 'WillyModule'

    static compileSdkVersion = 28
    static minSdkVersion = 21
    static targetSdkVersion = 28
    static versionCode = 1_000_000
    static versionName = '1.0.0'

    static gradlePluginVersion = '4.1.3'
    static kotlinVersion = '1.3.50'
    static ktxVersion = '1.2.0'
    static supportVersion = '28.1.1'

    static modules = [
            /*Don't delete this line*/
            /*Generated by "module_config.json"*/
            plugin_api_gradle_plugin   : new ModuleConfig(isApply: true , useLocal: true , localPath: "./plugin/api-gradle-plugin"),
            plugin_bus_gradle_plugin   : new ModuleConfig(isApply: true , useLocal: true , localPath: "./plugin/bus-gradle-plugin"),
            plugin_build_src_plugin    : new ModuleConfig(isApply: true , useLocal: true , localPath: "./plugin/buildSrc-plugin"),
            plugin_lib_base_transform  : new ModuleConfig(isApply: true , useLocal: true , localPath: "./plugin/lib/base-transform", remotePath: "io.github.weiliqiang:base-transform:1.0.6"),
            feature_mock               : new ModuleConfig(isApply: false, useLocal: true , localPath: "./feature/mock"),
            feature_launcher_app       : new ModuleConfig(isApply: true , useLocal: true , localPath: "./feature/launcher/app"),
            feature_launcher_export    : new ModuleConfig(isApply: true , useLocal: true , localPath: "./feature/launcher/export"),
            feature_launcher_pkg       : new ModuleConfig(isApply: true , useLocal: true , localPath: "./feature/launcher/pkg"),
            feature_feature0_app       : new ModuleConfig(isApply: false, useLocal: true , localPath: "./feature/feature0/app"),
            feature_feature0_export    : new ModuleConfig(isApply: true , useLocal: true , localPath: "./feature/feature0/export"),
            feature_feature0_pkg       : new ModuleConfig(isApply: true , useLocal: true , localPath: "./feature/feature0/pkg"),
            feature_feature1_app       : new ModuleConfig(isApply: false, useLocal: true , localPath: "./feature/feature1/app"),
            feature_feature1_export    : new ModuleConfig(isApply: true , useLocal: true , localPath: "./feature/feature1/export"),
            feature_feature1_pkg       : new ModuleConfig(isApply: true , useLocal: true , localPath: "./feature/feature1/pkg"),
            lib_base                   : new ModuleConfig(isApply: true , useLocal: true , localPath: "./lib/base", remotePath: "io.github.weiliqiang:lib_base:1.0.1"),
            lib_common                 : new ModuleConfig(isApply: true , useLocal: true , localPath: "./lib/common", remotePath: "io.github.weiliqiang:lib_common:1.0.1"),
            /*Don't delete this line*/
    ]

    static plugins = [
            plugin_gradle       : new PluginConfig(path: "com.android.tools.build:gradle:$gradlePluginVersion"),
            plugin_kotlin       : new PluginConfig(path: "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"),

            plugin_api          : new PluginConfig(isApply: true, useLocal: false, path: "io.github.weiliqiang:api-gradle-plugin:1.0.10", id: "io.github.weiliqiang.api"),
            plugin_bus          : new PluginConfig(isApply: true, useLocal: false, path: "io.github.weiliqiang:bus-gradle-plugin:1.0.2", id: "io.github.weiliqiang.bus"),
            plugin_buildSrc     : new PluginConfig(isApply: false, useLocal: false, path: "io.github.weiliqiang:buildSrc-plugin:1.0.1", id: "io.github.weiliqiang.buildSrc")
    ]

    static libs = [
            support_appcompat_v7        : new LibConfig(path: "com.android.support:appcompat-v7:$supportVersion"),
            support_design              : new LibConfig(path: "com.android.support:design:$supportVersion"),
            support_multidex            : new LibConfig(path: "com.android.support:multidex:1.0.2"),
            support_constraint          : new LibConfig(path: "com.android.support.constraint:constraint-layout:1.1.3"),

            kotlin                      : new LibConfig(path: "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlinVersion"),
            kotlin8                     : new LibConfig(path: "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlinVersion"),
            ktx                         : new LibConfig(path: "androidx.core:core-ktx:$ktxVersion"),
            kotlin_coroutines           : new LibConfig(path: "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.9"),
            kotlin_coroutines_Android   : new LibConfig(path: "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.9"),

            retrofit                    : new LibConfig(path: "com.squareup.retrofit2:retrofit:2.9.0"),
            okhttp                      : new LibConfig(path: "com.squareup.okhttp3:okhttp:4.9.3"),
            gson                        : new LibConfig(path: "com.google.code.gson:gson:2.9.0"),
            glide                       : new LibConfig(path: "com.github.bumptech.glide:glide:4.13.0"),
            glide_processor             : new LibConfig(path: "com.github.bumptech.glide:compiler:4.13.0"),
            utilcode                    : new LibConfig(path: "com.blankj:utilcode:1.28.0"),
            free_proguard               : new LibConfig(path: "com.blankj:free-proguard:1.0.1"),
            swipe_panel                 : new LibConfig(path: "com.blankj:swipe-panel:1.1"),
            commons_io                  : new LibConfig(path: "commons-io:commons-io:2.6"),

            leakcanary_android  : new LibConfig(path: "com.squareup.leakcanary:leakcanary-android:2.1"),
    ]
}